### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ariyawala** [ariyawala/furima-32539#11]
下記アプリの詳細です。
ご確認どうぞよろしくお願い致します。

フリマアプリのURL 
https://furima-32539.herokuapp.com/

Basic認証のIDとパスワード 
id: admin
pw: 2222

出品者用のメールアドレスとパスワード
email: test@test.com
pw: test111

購入者用のメールアドレスとパスワード 
email: test123@test.com
pw: test123

購入用カードの番号・期限・セキュリティコード
番号：PAY.JPのテストカード情報
期限：PAY.JPのテストカード情報
cvc：PAY.JPのテストカード情報

**Comment by TECHCAMP555** [comment]
ariyawalaさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・ユーザー本名は、名字と名前がそれぞれ必須であること
→漢字で入力すると以下のエラーがでます！
<img width="473" alt="スクリーンショット 2020-12-23 18 06 32" src="https://user-images.githubusercontent.com/69237012/102979776-e31a1a80-4549-11eb-8fa5-78d480d342ee.png">


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by ariyawala** [comment]
レビューありがとうございます。
バリデーションを修正しました。
ご確認お願いたします。

**Comment by TECHCAMP555** [comment]
ariyawalaさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・購入機能の挙動確認を行いますので下記情報を教えていただきたいです。

購入用カードの番号・期限・セキュリティコード
番号：PAY.JPのテストカード情報
期限：PAY.JPのテストカード情報
cvc：PAY.JPのテストカード情報



修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by ariyawala** [comment]
レビューありがとうございます。
テストカード情報下記となります。
ご確認お願いたします。


カード番号 ：4242424242424242（16桁）
CVC | 123
有効期限 | 1/21 以降

**Comment by TECHCAMP555** [comment]
ariyawala さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
